In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
u_w = np.array([[3],[1],[-2],[1]])
M_int_l = np.array([[50,0,250],[0,-50,250],[0,0,1]],float)
M_int_r = M_int_l
M_ext_l = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0]],float)
t_x = 0.2
M_ext_r = np.array([[1,0,0,-t_x],[0,1,0,0],[0,0,1,0]],float)

array([[ 1. ,  0. ,  0. , -0.2],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ]])

In [28]:
M_l = np.dot(M_int_l,M_ext_l)
M_r = np.dot(M_int_r,M_ext_r)

In [29]:
u_im_l = np.dot(M_l,u_w)
u_im_r = np.dot(M_r,u_w)
u_im_l_c = (u_im_l/u_im_l[-1])[0:-1]
u_im_r_c = (u_im_r/u_im_r[-1])[0:-1]

In [38]:
f_x = 50
d_x = u_im_l_c[0] - u_im_r_c[0]
z = t_x * f_x / d_x
x = z * (u_im_l_c[0]-250) / f_x
y = z * (u_im_l_c[1]-250) / -f_x

In [40]:
print(x,y,z)

[3.] [1.] [-2.]


In [68]:
C_1 = np.hstack((M_l,-u_im_l,np.zeros((3,1))))
C_2 = np.hstack((M_r,np.zeros((3,1)),-u_im_r))
C = np.vstack((C_1,C_2))

In [69]:
C

array([[ 50.,   0., 250.,   0., 350.,   0.],
       [  0., -50., 250.,   0., 550.,   0.],
       [  0.,   0.,   1.,   0.,   2.,   0.],
       [ 50.,   0., 250., -10.,   0., 360.],
       [  0., -50., 250.,   0.,   0., 550.],
       [  0.,   0.,   1.,   0.,   0.,   2.]])

In [70]:
U,S,V = np.linalg.svd(C)

In [71]:
u_w_svd_h = V[5,0:4]
u_w_svd_c = (u_w_svd_h/u_w_svd_h[-1])[0:-1]

In [72]:
u_w_svd_c 

array([ 3.,  1., -2.])

In [73]:
noise = np.random.normal(0, 0.1)

In [ ]:
u_im_l_noise = u_im_l - 